on: [push]
name: Azure ARM v2
jobs:
  build-and-deploy:
    env:
      apiManagementServiceName: 'rutzsco-demo-apiops'
      apiManagmentPublisherEmail: 'scrutz@microsoft.com'
      apiManagmentPublisherName: 'rutzsco'
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: CLI
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          ls

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: infrastructure/apim.bicep
        parameters: 'apiManagementServiceName=${{ vars.apiManagementServiceName }} apiManagmentPublisherEmail=${{ vars.apiManagmentPublisherEmail }} apiManagmentPublisherName=${{ vars.apiManagmentPublisherName }}'
        failOnStdErr: false
